apiVersion: v1
kind: Service
metadata:
  name: {{ include "pz-server.fullname" . }}
  labels:
    {{- include "pz-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: game
      protocol: UDP
      name: game
    - port: {{ .Values.service.queryPort }}
      targetPort: query
      protocol: UDP
      name: query
    - port: {{ .Values.service.rconPort }}
      targetPort: rcon
      protocol: TCP
      name: rcon
  selector:
    {{- include "pz-server.selectorLabels" . | nindent 4 }}